const {fs,path,By,Key,until,BASE_DIR,ensureDir,sleep,readLines,append,tgSendText,tgSendPhoto,buildDriver,screenshot,axios} = require('./common');

const PROFILE_PREFIX = process.env.PROFILE_PREFIX || 'joko';
const START_INDEX = parseInt(process.env.START_INDEX || '1',10);
const BASE_PROFILE_DIR = process.env.PROFILES_ROOT || path.join(BASE_DIR, 'chrome_profiles');
const EMAIL_FILE = path.join(BASE_DIR, 'email.txt');
const EMAILSHARE_FILE = path.join(BASE_DIR, 'emailshare.txt');
const MAPPING_FILE = path.join(BASE_DIR, 'mapping_profil.txt');
const HASIL_FILE = path.join(BASE_DIR, 'hasil.txt');
const AKUN_BERMASALAH = path.join(BASE_DIR, 'akun_bermasalah.txt');
const VNC_PORT = (process.env.VNC_PORT || '5900').trim();
const VNC_FILE = path.join(BASE_DIR, 'vnc.txt');
const TUNNEL_NOVNC_LOG = path.join(BASE_DIR, 'tunnel_novnc.log');
const TUNNEL_NOVNC_URL_FILE = path.join(BASE_DIR, 'novnc_url.txt');
const TUNNEL_LOG = path.join(BASE_DIR, 'tunnel.log');
const TUNNEL_URL_FILE = path.join(BASE_DIR, 'tunnel_url.txt');
ensureDir(BASE_PROFILE_DIR); for(const f of [EMAIL_FILE,EMAILSHARE_FILE,MAPPING_FILE,HASIL_FILE]){ if(!fs.existsSync(f)) fs.writeFileSync(f,''); }
function nowName(){ return new Date().toISOString().replace(/[-:T.]/g,'_').slice(0,19); }
async function getPublicIp(){ try{ const r=await axios.get('https://ifconfig.me',{timeout:8000}); return String(r.data).trim(); }catch(e){ return 'Unknown IP'; } }
function slugName(v){ return String(v||'joko-idx').toLowerCase().replace(/[^a-z0-9-]+/g,'-').replace(/^-+|-+$/g,'').slice(0,40) || 'joko-idx'; }
function appName(projectNo, label){ const base = slugName(process.env.APP_NAME_PREFIX || path.basename(BASE_DIR) || 'joko-idx'); return `${base}-${label}-${projectNo}`.slice(0,60); }
async function takeShot(driver, prefix){ return screenshot(driver, path.join(BASE_DIR, `${prefix}_${nowName()}.png`)); }
async function isGoogleChallenge(driver){ try{ const u=(await driver.getCurrentUrl()).toLowerCase(); return ['challenge','signin/v2/challenge','approval','verify'].some(k=>u.includes(k)); }catch(e){ return false; } }
async function waitUntilNotRedirectToLogin(driver, timeout=60){ const t=Date.now(); while(Date.now()-t < timeout*1000){ let u=''; try{ u=(await driver.getCurrentUrl()).toLowerCase(); }catch(e){} if(u.includes('studio.firebase.google.com')||u.includes('idx.google.com')||u.includes('firebase.google.com')) return true; if(await isGoogleChallenge(driver)) return false; await sleep(1000); } return false; }
function saveMapping(profileDir,label){ append(MAPPING_FILE, `${profileDir}|${label}\n`); }
function createFirstRun(profileDir){ ensureDir(profileDir); fs.writeFileSync(path.join(profileDir,'First Run'),''); }
async function getTunnelUrl(timeout=25){ const env=(process.env.NOVNC_TUNNEL_URL||'').trim(); if(env.startsWith('https://')) return env; for(const f of [TUNNEL_NOVNC_URL_FILE]){ try{ const s=fs.readFileSync(f,'utf8').trim(); if(s.startsWith('https://')) return s; }catch(e){} } const start=Date.now(); while(Date.now()-start<timeout*1000){ try{ const log=fs.readFileSync(TUNNEL_NOVNC_LOG,'utf8'); const m=log.match(/https:\/\/[a-zA-Z0-9.-]+\.trycloudflare\.com/); if(m){ fs.writeFileSync(TUNNEL_NOVNC_URL_FILE,m[0]+'\n'); return m[0]; } }catch(e){} await sleep(1000); } const env2=(process.env.TUNNEL_URL||'').trim(); if(env2.startsWith('https://')) return env2; for(const f of [TUNNEL_URL_FILE,TUNNEL_LOG]){ try{ const s=fs.readFileSync(f,'utf8'); const m=s.match(/https:\/\/[a-zA-Z0-9.-]+\.trycloudflare\.com/); if(m) return m[0]; if(s.trim().startsWith('https://')) return s.trim(); }catch(e){} } return null; }
async function notifyVncVerification(driver,label,email,reason='OTP/Verification terdeteksi'){ const url=await getTunnelUrl(25); const ss=await takeShot(driver, `verify_${label}`); let msg=`⚠️ ${reason}\nAkun: ${label}\nEmail: ${email}\n`; msg += url ? `\n🖥️ noVNC (via Tunnel):\n${url}\n` : `\n❗ Tunnel URL belum kebaca. Pastikan cloudflared noVNC tunnel jalan.\n`; await tgSendText(msg); if(ss) await tgSendPhoto(msg, ss); console.log(msg); }
async function waitManualVerification(driver,label,email,timeout=900){ await notifyVncVerification(driver,label,email,'OTP/Verification Google terdeteksi setelah input password'); const start=Date.now(); let last=0; while(Date.now()-start<timeout*1000){ if(!(await isGoogleChallenge(driver))) return true; if(Date.now()-last>60000){ last=Date.now(); await tgSendText(`⏳ Masih menunggu verifikasi manual...\nAkun: ${label}\nEmail: ${email}\n(${Math.floor((Date.now()-start)/1000)}s/${timeout}s)`); } await sleep(2000); } const ss=await takeShot(driver, `verify_timeout_${label}`); await tgSendText(`⛔ Timeout verifikasi manual.\nAkun: ${label}\nEmail: ${email}`); if(ss) await tgSendPhoto(`⛔ Timeout verifikasi manual ${label} (${email})`, ss); return false; }
async function googleLogin(driver,email,password,label){ await driver.get('https://accounts.google.com/ServiceLogin?hl=en&continue=https%3A%2F%2Fstudio.firebase.google.com%2F'); await sleep(3000); try{ const cur=(await driver.getCurrentUrl()).toLowerCase(); if(!cur.includes('accounts.google.com')) return true; }catch(e){}
  try{ try{ const useOther=await driver.wait(until.elementLocated(By.xpath("//*[contains(text(),'Use another account')]")),3000); await useOther.click(); await sleep(1000); }catch(e){} const emailBox=await driver.wait(until.elementLocated(By.id('identifierId')),30000); await emailBox.click(); await emailBox.clear(); await emailBox.sendKeys(email); try{ await driver.findElement(By.id('identifierNext')).click(); }catch(e){ await emailBox.sendKeys(Key.ENTER); } console.log(`[✅] Input email: ${email}`); }catch(e){ const ss=await takeShot(driver, `email_input_fail_${label}`); if(ss) await tgSendPhoto(`❌ Gagal input email ${label} (${email})\n${e}`, ss); return false; }
  await sleep(2000); try{ const passBox=await driver.wait(until.elementLocated(By.name('Passwd')),30000); await passBox.click(); await passBox.clear(); await passBox.sendKeys(password); try{ await driver.findElement(By.id('passwordNext')).click(); }catch(e){ await passBox.sendKeys(Key.ENTER); } console.log('[✅] Input password & Next'); }catch(e){ const ss=await takeShot(driver, `pass_input_fail_${label}`); if(ss) await tgSendPhoto(`❌ Gagal input password ${label} (${email})\n${e}`, ss); return false; }
  await sleep(3000); if(await isGoogleChallenge(driver)){ if(!(await waitManualVerification(driver,label,email,900))) return false; } await driver.get('https://studio.firebase.google.com/'); await sleep(5000); const ok=await waitUntilNotRedirectToLogin(driver,120); if(!ok && (await driver.getCurrentUrl()).toLowerCase().includes('accounts.google.com')){ const ss=await takeShot(driver, `login_stuck_${label}`); if(ss) await tgSendPhoto(`❌ Login stuck ${label} (${email})`, ss); return false; } return true; }
async function openFirebaseAndAccept(driver){ await driver.get('https://studio.firebase.google.com/'); await sleep(15000); try{ await driver.executeScript("document.getElementById('utos-checkbox').click();"); console.log("[✅] Klik checkbox 'I accept'"); }catch(e){ console.log("[SKIP] Step: 'I accept' tidak ditemukan"); } try{ const btn=await driver.wait(until.elementLocated(By.xpath('/html/body/app-root/ui-loader/onboarding-wrapper/single-column-layout/div/div[2]/onboarding-welcome-v2/div/form/div[2]/button/span')),30000); await btn.click(); await sleep(1000); }catch(e){ console.log("[SKIP] Step: tombol 'Confirm' tidak ditemukan"); } }
async function createExpressProject(driver, projectNo, label, email){ try{ await driver.get('https://studio.firebase.google.com/new/express'); await sleep(5000); const input=await driver.wait(until.elementLocated(By.xpath('/html/body/app-root/ui-loader/new-template-app/single-column-layout/div/div/form/div[1]/input')),30000); const app=appName(projectNo, label); await input.clear(); await input.sendKeys(app); console.log(`[✅] Isi nama app dari folder/file (project ${projectNo}): ${app}`); await input.sendKeys(Key.ENTER); await sleep(15000); const link=await driver.getCurrentUrl(); append(HASIL_FILE, link+'\n'); console.log(`[✅] Link tersalin dan disimpan (project ${projectNo}): ${link}`); await sleep(3000); return true; }catch(e){ const ss=await takeShot(driver, `error_project_${projectNo}_${label}`); const cap=`⚠️ ERROR membuat link project ke-${projectNo}\nAkun: ${label}\nEmail: ${email}\nError: ${e}`; await tgSendText(cap); if(ss) await tgSendPhoto(cap, ss); return false; } }
async function joinOnboarding(driver){ try{ await driver.get('https://studio.firebase.google.com/'); await sleep(5000); const b=await driver.wait(until.elementLocated(By.xpath('/html/body/app-root/ui-loader/firebase-studio-dashboard/idx-app-chrome/div/div[2]/div[1]/div[2]/devprofile-onboarding/div/div/div/div/button')),30000); await b.click(); await sleep(10000); const input=await driver.wait(until.elementLocated(By.xpath('/html/body/app-root/wrapper-dialog/single-column-layout/div/div[2]/onboarding-dialog/div/form/div[1]/input')),30000); await input.click(); await input.sendKeys('Indonesia', Key.TAB, 'A'); const c=await driver.wait(until.elementLocated(By.xpath('//html/body/app-root/wrapper-dialog/single-column-layout/div/div[2]/onboarding-dialog/div/div/div/button[2]/span')),30000); await c.click(); await sleep(5000); return true; }catch(e){ console.log(`[SKIP] Step failed: ${e}`); return false; } }
async function shareWorkspaces(driver,label,email){ await driver.get('https://studio.firebase.google.com/'); await sleep(7000); if(!fs.existsSync(EMAILSHARE_FILE)) fs.writeFileSync(EMAILSHARE_FILE,''); const shareEmail=fs.readFileSync(EMAILSHARE_FILE,'utf8').trim(); if(!shareEmail){ await tgSendText('⚠️ emailshare.txt kosong. Step share dilewati.'); return; } for(let i=1;i<=10;i++){ try{ const titik=`/html/body/app-root/ui-loader/firebase-studio-dashboard/idx-app-chrome/div/div[2]/div[2]/div/your-workspaces/div[2]/workspace[${i}]/div/div/button/mat-icon`; const t=await driver.wait(until.elementLocated(By.xpath(titik)),30000); await t.click(); await sleep(1000); const share=await driver.wait(until.elementLocated(By.xpath("//div[contains(@class, 'cdk-overlay-container')]//button[normalize-space()='Share']")),5000); await share.click(); await sleep(1000); const add=await driver.wait(until.elementLocated(By.xpath('/html/body/div[6]/div/div[2]/mat-dialog-container/div/div/share-dialog/div/div[2]/input')),30000); await add.click(); await add.sendKeys(shareEmail, Key.ENTER); await sleep(2000); const conf=await driver.wait(until.elementLocated(By.xpath('/html/body/div[6]/div/div[2]/mat-dialog-container/div/div/share-dialog/div/div[3]/div[2]/button/span')),30000); await conf.click(); await sleep(10000); }catch(e){ console.log(`[❌] Gagal workspace ke-${i}: ${e}`); } } await tgSendText(`✅ Share workspace selesai untuk ${label} (${email}).`); }
async function main(){ const vpsIp=await getPublicIp(); const accounts=readLines(EMAIL_FILE).filter(l=>l.includes('|')).map(l=>{ const [email,...p]=l.split('|'); return {email:email.trim(), password:p.join('|').trim()}; }); if(!accounts.length){ console.log(`❌ email.txt kosong/tidak valid: ${EMAIL_FILE}`); return; } fs.writeFileSync(MAPPING_FILE,''); let idx=START_INDEX; for(const acc of accounts){ const label=`${PROFILE_PREFIX}${idx++}`; const profileDir=path.join(BASE_PROFILE_DIR,label); ensureDir(profileDir); if(!fs.existsSync(path.join(profileDir,'First Run'))) createFirstRun(profileDir); saveMapping(profileDir,label); console.log(`\n${'='.repeat(60)}\n[👤] PROSES AKUN: ${label} | ${acc.email}\n${'='.repeat(60)}`); await tgSendText(`🚀 Mulai proses akun\nLabel: ${label}\nEmail: ${acc.email}\nIP: ${vpsIp}`); let driver=null; try{ driver=await buildDriver(profileDir,'Default',['--start-maximized']); const ok=await googleLogin(driver, acc.email, acc.password, label); if(!ok){ await tgSendText(`❌ Login gagal untuk ${label} (${acc.email}).`); append(AKUN_BERMASALAH, `${acc.email}|${acc.password}  # Login gagal\n`); try{ const ss=await takeShot(driver, `login_fail_${label}`); if(ss) await tgSendPhoto(`❌ Login gagal ${label} (${acc.email})`, ss); }catch(e){} continue; } await openFirebaseAndAccept(driver); for(let p=1;p<=3;p++) await createExpressProject(driver,p,label,acc.email); await joinOnboarding(driver); for(let p=4;p<=10;p++){ const okp=await createExpressProject(driver,p,label,acc.email); if(p>=6 && p<10) await sleep(65000); if(p===10){ await tgSendText(okp ? `✅ Akun ${label} (${acc.email}) berhasil membuat 10 project Firebase.` : `⚠️ Akun ${label} (${acc.email}) gagal di project ke-10.`); if(okp) await sleep(15000); } } await shareWorkspaces(driver,label,acc.email); await tgSendText(`✅ PROSES SELESAI untuk ${label} (${acc.email}).`); }catch(e){ console.log(`[❌ ERROR GLOBAL] ${label} ${acc.email}: ${e}`); await tgSendText(`❌ ERROR GLOBAL\nLabel: ${label}\nEmail: ${acc.email}\nError: ${e}`); append(AKUN_BERMASALAH, `${acc.email}|${acc.password}  # Error global\n`); }finally{ if(driver) try{ await driver.quit(); }catch(e){} await sleep(2000); } } console.log('\n✅ Semua akun selesai diproses.'); }
main().catch(e=>{ console.error(e); process.exit(1); });
